name: Build and Publish Docker Image

on:
  push:
    branches:
      - master  # Trigger on push to the main branch

jobs:
  build-and-push-teseapi:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
      - name: Build and push Docker image teseapi
        uses: docker/build-push-action@v4
        with:
          context: TeseAPIs # Path to the Dockerfile
          push: true
          tags: nunodinis93/teseapi
          
      # Build the Docker image
      - name: Build and push Docker image teseblazor
        uses: docker/build-push-action@v4
        with:
          context: Tese_Blazor # Path to the Dockerfile
          push: true
          tags: nunodinis93/teseblazor
